---
# tasks file for mywebserver
  ---
    - name: install httpd package
      ansible.builtin.yum:
        name: httpd
        state: latest
      notify:
        - restart apache
    - name: copy index page
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
    - name: add firewall rule
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
    - name: restart apache
      service:
        name: httpd
        enabled: true
        state: started
